version: "3"
services:
  react:
    build:
      context: .
      dockerfile : Dockerfile_dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./:/app
    stdin_open: true

